server:
  port: 8082

spring:
  profiles:
    active: dev
  datasource:
    name: inventory
    url: jdbc:mysql://localhost:3306/hospital?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    connect-timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

  tengxun:
    accessKey: AKID0keV8TMlv8pBSV7GLhsx3tU4QjSxlDuS
    secretKey: eBFLCA3hppL2NVNAk4BC5osjesvlDbhy
    bucket: ap-guangzhou
    bucketName: wxmall2-1305281846
    path: https://wxmall2-1305281846.cos.ap-guangzhou.myqcloud.com
    qianzui: hospital
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
config:
  accessToken-expireTime: 3600
  #  refreshToken-expireTime: 604800
  refreshToken-expireTime: 604800
  encrypt-jwtKey: U0JBUElOENhspJrzkyNjQ1NA



